### ISSUE TITLE
Always yielding "Couldn't find youtube video" Error

### ISSUE THREAD

**Issue by lkxiii** [hellozimi/HCYoutubeParser#29]
The videoDictionary in h264videosWithYoutubeID is returning nothing. It was working fine yesterday. maybe there's some update from Youtube.

Edit: changed "sig" to "itag", I don't know if this is correct but it worked for me.

**Comment by krin-san** [comment]
Commit https://github.com/hellozimi/HCYoutubeParser/commit/4d15df43739ed2ecee7acebacef0aa40264ba9af already fixed this issue. Let's close it.
