### ISSUE TITLE
how do i use this to create a youtube ID that works

### ISSUE THREAD

**Issue by sophiebowmann** [hellozimi/HCYoutubeParser#42]
i'm using a site called buzz touch and it had a link to this page saying to use it to create the right youtube ID to upload a video.

This is the video i uploaded to youtube:
https://www.dropbox.com/s/qhxgxgu35y7o4ou/Screenshot%202014-08-06%2018.36.01.png 

The instructions i received were:
This plugin uses the HCYoutubeParser to get the iOS compatible video URL from YouTube. 
https://github.com/hellozimi/HCYoutubeParser 

Thank you

**Comment by hellozimi** [comment]
Hi, I can not help you with this. You have to contact buzztouch about this. Take care.
