### ISSUE TITLE
background play

### ISSUE THREAD

**Issue by syrakozz** [hellozimi/HCYoutubeParser#49]
how i can play the video in background so i can still listen to the song, 
ans appear on the lock screen

**Comment by hellozimi** [comment]
This isn't something which should be provided by this framework. Please see Apples Developer Documentation for this feature in [MPMoviePlayerViewController](https://developer.apple.com/library/ios/documentation/MediaPlayer/Reference/MPMoviePlayerViewController_class/index.html).
