### ISSUE TITLE
Add Start time and End time in HCYoutubeParser

### ISSUE THREAD

**Issue by pothirajp** [hellozimi/HCYoutubeParser#52]
Hi i am using your libraries in my project. i am struggling add start time and End time , can u advice me how to add that ?

**Comment by hellozimi** [comment]
You have to ask the `MPMoviePlayer` for the length when the content is actually playable. See [this](http://stackoverflow.com/a/9039538/356338).

**Comment by pothirajp** [comment]
Thank you Mr. hellozimi
