### ISSUE TITLE
Some of YouTube videos can't be parsed: "This video contains content from VEVO. It is restricted from playback on certain sites."

### ISSUE THREAD

**Issue by andrew8712** [hellozimi/HCYoutubeParser#53]
I run [HCYoutubeParser h264videosWithYoutubeURL: completeBlock:] method, where URL == "https://youtu.be/YQHsXMglC9A".

However, the request returns this (a value of responseString variable):

cos=Macintosh&eventid=Q4YsVpHHAcGYYuWDgaAM&errordetail=0&cosver=10_8_2&status=fail&errorcode=150&reason=This+video+contains+content+from+VEVO.+It+is+restricted+from+playback+on+certain+sites.%3Cbr%2F%3E%3Cu%3E%3Ca+href%3D%27http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYQHsXMglC9A%26feature%3Dplayer_embedded%27+target%3D%27_blank%27%3EWatch+on+YouTube%3C%2Fa%3E%3C%2Fu%3E&enablecsi=1&cbrver=22.0.1229.79&csi_page_type=embed&c=WEB&cbr=Chrome

It seems it has something to do with get_video_info method, please see this page: http://stackoverflow.com/questions/22125353/youtube-this-video-contains-content-from-vevo

**Comment by Pranoy1c** [comment]
same problem here, is there a way to fix this?

**Comment by Keyar** [comment]
Same Problem for me & Even I tried with get_video_info to get the Video URL, but its not working. Where as its good & working in Same kind of parser in Android. Can anyone else?

**Comment by andrew8712** [comment]
Any comments why did you close this issue? Was it resolved?

**Comment by hellozimi** [comment]
This has been discussed in previous issues and no one has submitted a pull request to fix it. This project isn't being maintained any more so I just thought of doing a bit of cleaning.
