### ISSUE TITLE
I have two Videos, one can play, the other cannot

### ISSUE THREAD

**Issue by BorisJia** [hellozimi/HCYoutubeParser#65]
You could test using these two urls for the "some videos cannot play" issue.

https://www.youtube.com/watch?v=r45MkeFDjMU     // this one cannot play

https://www.youtube.com/watch?v=gjbiZQYE6o0       // this one work well

**Comment by hellozimi** [comment]
This project isn't being maintained any more. My best guess would be to talk to YouTube directly cause this project is just a wrapper around their API.
